### ISSUE TITLE
Make the sidebar close icon white in the mobile view

### ISSUE THREAD

**Issue by hemantwasthere** [hemantwasthere/Genius#1]
![image](https://github.com/hemantwasthere/genius/assets/85151171/21871559-ad04-4a56-ba84-6bd9f229c4d0)

As you can see the sidebar close icon is black in the mobile view, make it white or any so that it can be visible clearly.

**Comment by rockingrohit9639** [comment]
@hemantwasthere Can I work on this ?

**Comment by hemantwasthere** [comment]
@rockingrohit9639 sure go ahead, assigning to you!

**Comment by bilalmirza74** [comment]
still available?
@hemantwasthere
